Repository teacher-coder/picture-muvie, pull requests merged in 2023-02, with the labels that each got.

#4 1 feat search lyrics
  manage.py
  picture_muvie/api.py
  picture_muvie/asgi.py
  picture_muvie/settings.py
  picture_muvie/urls.py
  picture_muvie/utils/__init__.py
  picture_muvie/utils/search_lyrics.py
  picture_muvie/wsgi.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#3 Feat: makedocx app 추가
  picture_muvie/api.py
  picture_muvie/docs.py
  picture_muvie/settings.py
  picture_muvie/urls.py
  pyproject.toml
  templates/lyrics_body_form.docx
  templates/lyrics_header_form.docx
Labels: enhancement

#8 6 feature textarea for splitting lyrics
  frontend/index.html
  frontend/src/components/TheFooter.vue
  frontend/src/components/TheHeader.vue
  frontend/src/views/HomeView.vue
Labels: enhancement

#10 9 feature frontend api 연결
  picture_muvie/api.py
  picture_muvie/docs.py
  picture_muvie/settings.py
  picture_muvie/urls.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#35 29 파일 포맷에 대한 유저 선택 UI 제작 해당 데이터 be 전달
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/modules/lyrics.js
  frontend/src/components/ButtonDropDown.vue
  frontend/src/utils.js
  frontend/src/views/HomeView.vue
Labels: enhancement

#36 feat: different margin size for xl and lg
  frontend/index.html
Labels: enhancement

#33 feat: show rotating icon when searching
  frontend/src/views/HomeView.vue
Labels: enhancement

#40 docx 파일 생성 로직 refactoring
  backend/.env.sample
  backend/picture_muvie/api.py
  backend/picture_muvie/docs.py
  backend/picture_muvie/settings.py
  backend/picture_muvie/templates/title.docx
  backend/poetry.lock
  backend/pyproject.toml
  backend/templates/lyrics_body_form.docx
  backend/templates/lyrics_header_form.docx
  frontend/src/views/HomeView.vue
Labels: bug, enhancement

#43 FEAT/LyricDocx : 가사 수정창 줄 수 조정, 적응형 문서 생성
  backend/picture_muvie/api.py
  backend/picture_muvie/docs.py
  backend/picture_muvie/utils/optimize_lyrics.py
  frontend/src/utils.js
  frontend/src/views/HomeView.vue
Labels: enhancement

#42 41 chore readme 파일
  README.md
  images/019a2c161f67509e8f56e03373494fca5d02cadbd0f500fad0fad97db867ec85.png
  images/63e9e641ac72672596c28e425c56a0863be542810cc664731e97cc1f7f401cb5.png
  images/dfd64ca7317cc37fad97e5a7df629354c1e18d1912f268e7acb4244fb9e8034a.png
  images/screenshot.png
Labels: documentation

#53 Docker local settings
  .dockerignore
  README.md
  docker-compose.dev.yml
  frontend/Dockerfile
Labels: bug, documentation, enhancement

#52 49 feat button for adjusting lyrics compress offset
  .gitignore
  frontend/src/utils.js
  frontend/src/views/HomeView.vue
Labels: enhancement

#57 56 lint for tailwind with prettier
  frontend/.prettierrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ButtonDropDown.vue
  frontend/src/components/TheFooter.vue
  frontend/src/components/TheHeader.vue
  frontend/src/views/HomeView.vue
Labels: enhancement

#58 Feat/docker production
  .dockerignore
  .gitignore
  backend/.env.sample
  backend/picture_muvie/settings.py
  backend/scripts/start_prod.sh
  docker-compose.yml
  frontend/.prettierrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ButtonDropDown.vue
  frontend/src/components/TheFooter.vue
  frontend/src/components/TheHeader.vue
  frontend/src/views/HomeView.vue
  nginx/Dockerfile
  nginx/prod.conf
Labels: enhancement

#59 fix: remove dark mode
  frontend/src/views/HomeView.vue
Labels: bug

#62 페이지 번호 추가 + 폰트 사이즈 최적화
  backend/picture_muvie/docs.py
  backend/picture_muvie/utils/optimize_lyrics.py
Labels: bug, enhancement

#67 Apply logging system
  backend/picture_muvie/api.py
  backend/picture_muvie/settings.py
  backend/picture_muvie/utils/search_lyrics.py
Labels: enhancement

#80 naver api call_logging 수정
  backend/picture_muvie/api.py
  backend/picture_muvie/utils/naver_search.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main.js
  frontend/src/views/HomeView.vue
Labels: enhancement

#84 제목, 가수명 스크래핑 및 프론트엔드 적용
  backend/picture_muvie/api.py
  backend/picture_muvie/utils/naver_search.py
  backend/picture_muvie/utils/scraper.py
  frontend/src/utils.js
  frontend/src/views/HomeView.vue
Labels: bug, enhancement
